insert into prodotto values 
("001", "Greco di Tufo DOCG", 8.50,"bianco","https://www.collinedelsole.it/wp-content/uploads/2019/01/GRECO-DI-TUFO-DOCG-1-768x768.jpg","Il greco di Tufo è uno dei vitigni autoctoni a bacca bianca più antichi del sud Italia. È arrivato in Campania ai tempi della colonizzazione greca, molto probabilmente dalla regione della Tessaglia. Si è diffuso prima nell’area vesuviana, per poi trovare le migliori condizioni pedoclimatiche nelle aree più interne dell’avellinese, anche grazie ai terreni di matrice vulcanica e al clima più fresco e continentale. Produce grappoli piuttosto piccoli e serrati, con acini di piccole dimensioni. È un vitigno a maturazione tardiva, per solito viene vendemmiato verso metà ottobre e va vinificato con attenzione, per evitare il pericolo di ossidazioni. Il vino greco di Tufo ha un colore giallo paglierino, con bouquet dalle fresche note agrumate, fruttate, con nitidi sentori minerali. Il sorso è ampio, con bel frutto, buona freschezza e mineralità. Il finale è leggermente ammandorlato. Grazie alla sua struttura e acidità, ha una buona propensione all’invecchiamento. Greco di Tufo Docg si degusta a una temperatura di 8/10 °C. A tavola accompagna molto bene i primi piatti di mare, i crostacei e pesci saporiti. Tra gli abbinamenti territoriali, interessanti quelli con la mozzarella di bufala e con la pizza."),
("002", "Taurasi DOCG", 17.00,"rosso", "https://www.collinedelsole.it/wp-content/uploads/2019/01/TAURASI-DOCG-1-300x300.jpg","Il Taurasi è un vino a DOCG prodotto nella provincia di Avellino a cui nel 2011 è stato cambiato il nome per cui dovrà per il futuro essere commercializzato con l'etichetta Taurasi rosso rispettando il nuovo disciplinare.Il vino deve essere sottoposto ad un periodo di invecchiamento obbligatorio di almeno tre anni di cui almeno uno in botti di legno.Il periodo di invecchiamento decorre dal primo dicembre dell'annata di produzione delle uve.A scopo migliorativo è consentita l'aggiunta di vino Taurasi più giovane ad identico vino più vecchio, o viceversa, nella misura massima del 15% nel rispetto delle disposizioni CEE in materia.In tal caso in etichetta dovrà figurare il millesimo (annata) del vino che concorre in misura preponderante.La resa massima delle uve in vino non deve essere superiore al 70% al primo travaso e non dovrà superare il sessantacinque per cento dopo il periodo di invecchiamento obbligatorio."),
("003", "Taurasi DOCG MAGNUM", 40.00,"rosso", "https://www.collinedelsole.it/wp-content/uploads/2020/11/magnum-taurasi-300x300.jpg", "Il Taurasi è un vino a DOCG prodotto nella provincia di Avellino a cui nel 2011 è stato cambiato il nome per cui dovrà per il futuro essere commercializzato con l'etichetta Taurasi rosso rispettando il nuovo disciplinare.Il vino deve essere sottoposto ad un periodo di invecchiamento obbligatorio di almeno tre anni di cui almeno uno in botti di legno.Il periodo di invecchiamento decorre dal primo dicembre dell'annata di produzione delle uve.A scopo migliorativo è consentita l'aggiunta di vino Taurasi più giovane ad identico vino più vecchio, o viceversa, nella misura massima del 15% nel rispetto delle disposizioni CEE in materia.In tal caso in etichetta dovrà figurare il millesimo (annata) del vino che concorre in misura preponderante.La resa massima delle uve in vino non deve essere superiore al 70% al primo travaso e non dovrà superare il sessantacinque per cento dopo il periodo di invecchiamento obbligatorio."),
("004", "Fiano di Avellino DOCG", 8.50,"bianco", "https://www.collinedelsole.it/wp-content/uploads/2019/01/FIANO-DI-AVELLINO-DOCG-1-300x300.jpg","La zona di produzione del Fiano di Avellino DOP comprende l'intero territorio dei comuni di Avellino, Lapio, Atripalda, Cesinali, Aiello del Sabato, S. Stefano del Sole, Sorbo Serpico, Salza Irpina, Parolise, S. Potito Ultra, Candida, Manocalzati, Pratola Serra, Montefredane, Grottolella, Capriglia Irpina, S. Angelo a Scala, Summonte, Mercogliano, Forino, Contrada, Monteforte Irpino, Ospedaletto D'Alpinolo, Montefalcione, Santa Lucia di Serino e San Michele di Serino in provincia di Avellino, nella regione Campania.Il Fiano di Avellino DOP ha un colore giallo paglierino più o meno intenso. Il bagaglio aromatico si esprime al naso con note di nocciola, mandorla, rosmarino, nespola ed erbe aromatiche. Al gusto è intenso e avvolgente con toni minerali e sapidi e un retrogusto tipico con richiami agrumati. Può presentare la menzione Riserva dopo un periodo di invecchiamento obbligatorio di almeno 12 mesi; il periodo di invecchiamento decorre dal primo novembre dell’annata di produzione delle uve. Le uve destinate alla vinificazione devono assicurare al Fiano di Avellino DOP e Fiano di Avellino DOP Riserva un titolo alcolometrico minimo, rispettivamente di almeno 11,5% vol. e 12% vol."),
("005", "Irpinia Aglianico DOC", 8.50, "rosso", "https://www.collinedelsole.it/wp-content/uploads/2019/02/IRPINIA-AGLIANICO-DOC-1-600x600-1-300x300.jpg","Un vino brillante, di colore rosso rubino e consistente. Al naso è un vino intenso e complesso, con note di frutti di bosco maturi e spezie dolci. Al palato risulta caldo, morbido e dotato di buona freschezza e sapidità, con tannini fini e vellutati. Equilibrato, intenso e persistente."),
("006", "Irpinia Aglianico DOC MAGNUM", 30.00,"rosso", "https://www.collinedelsole.it/wp-content/uploads/2020/11/magnum-aglianico-300x300.jpg","Un vino brillante, di colore rosso rubino e consistente. Al naso è un vino intenso e complesso, con note di frutti di bosco maturi e spezie dolci. Al palato risulta caldo, morbido e dotato di buona freschezza e sapidità, con tannini fini e vellutati. Equilibrato, intenso e persistente."),
("007", "Falanghina Irpinia DOC", 8.50,"bianco", "https://www.collinedelsole.it/wp-content/uploads/2019/01/Irpinia-Falanghina-DOC-1-768x768.jpg","Secondo la tradizione, il vino Irpinia Falanghina D.O.C. discenderebbe  dall’antico “Falerno bianco”, un vitigno che si trova esclusivamente in  Campania. Proprio questa origine e appartenenza esclusiva  della Falanghina D.O.C., ha spinto nel tempo alcuni produttori vinicoli di  altre regioni al tentativo di rivendicare la paternità. Un fenomeno  particolarmente diffuso a partire dal 1990 e prontamente osteggiato dai  produttori dell’Irpinia.Irpinia Falanghina D.O.C. è un vino bianco ben strutturato ed armonico,  frutto della vinificazione delle omonime e pregiate uve  di Falanghina D.O.C., ad Avellino, in Irpinia. Dal gusto piacevole e definito, il vino Irpinia Falanghina D.O.C. unisce  corposità ad una raffinatissima aromaticità. Questo vino, infatti, si presenta  con un profumo fruttato al gusto di pera, arricchito da un retrogusto quasi  floreale, con deliziose note di mandorla amarognola. Irpinia  Falanghina D.O.C. è un vino dal sapore secco e fresco, e ha una  gradazione di 12,5 gradi. Fermentato in vasche  d’acciaio, Falanghina D.O.C. è consigliato per piatti a base di pesce, carni  bianche e dolci. "),
("008", "Falanghina Sannio DOC", 8.50,"bianco", "https://www.collinedelsole.it/wp-content/uploads/2019/01/FALANGHINASannio-DOC-1-300x300.jpg","La denominazione di origine controllata «Falanghina del Sannio» è riservata, inoltre, ai vini bianchi per le seguenti categorie e tipologie: spumante, spumante di qualità, spumante di qualità metodo classico, vendemmia tardiva, passito ( anche con la specificazione di una delle seguenti sottozone:«Guardia Sanframondi o Guardiolo», «Sant'Agata dei Goti», «Solopaca», «Taburno»).Si accompagna bene a primi di pesce , ai crostacei, a piatti a base di carni bianche e a formaggi non troppo stagionati."),
("009", "Greco spumante Brut ", 9.00,"spumante","https://www.collinedelsole.it/wp-content/uploads/2019/02/Spumante-greco-di-tufo-600x600-1-300x300.jpg","Il vino Greco di Tufo spumante DOCG è una delle tipologie di vino previste dalla denominazione Greco di Tufo DOCG, una DOCG della regione . I disciplinari delle denominazioni DOCG prevedono al loro interno specifiche tipologie di vino, che si caratterizzano per la loro composizione ampelografica, ossia per i vitigni ammessi per la loro produzione, per le procedure di vinificazione e per le specifiche caratteristiche organolettiche del vino. I vitigni che rientrano nella composizione del vino Greco di Tufo spumante DOCG sono Greco min.85%, Coda di Volpe max.15%. Le caratteristiche organolettiche del Greco di Tufo spumante DOCG prevedono un colore Giallo paglierino, con bollicine bollicine fini, bollicine persistenti; Il profilo olfattivo del vino Greco di Tufo spumante DOCG è caratteristico, piacevole, delicato e al palato risulta sapido, armonico, secco, Brut, Extra dry."),
("010", "Greco Campania IGT", 5.50,"bianco", "https://www.collinedelsole.it/wp-content/uploads/2019/01/GRECO-CAMPANIA-IGT-1-300x300.jpg","Caratteristiche: Colore giallo paglierino con leggeri riflessi verdolini, limpido e consistente, profumo intenso, ampio con note minerali. Sapore secco robusto con freschezza minerale persistente. Primi piatti con frutti di mare, carni di pollo e coniglio alla brace e per la sua freschezza minerale su zuppe di verdure e legumi, va servito ad una temperatura di 8°-10° C."),
("011", "Irpinia Coda di Volpe DOC", 8.50,"spumante", "https://www.collinedelsole.it/wp-content/uploads/2020/11/coda-di-volpe-600x600-1-300x300.jpg","Coda di Volpe Irpinia è un vino D.O.C. di colore giallo paglierino brillante, dal sapore intenso e fruttato.Il vino si presenta con la forma caratteristica di un grande grappolo con piccoli acini. Note di agrumi e mela cotogna donano al vino Coda di Volpe una consistenza morbida e fresca al palato.Profumo delicato per questo vino dell’Irpinia che si accompagna piacevolmente ad antipasti di mare, primi delicati e a base di pesce. Coda di Volpe viene inoltre utilizzato anche con piatti di carne."),
("012", "Aglianico Campania IGT", 5.50,"rosso", "https://www.collinedelsole.it/wp-content/uploads/2019/01/AGLIANICO-IGT-1-300x300.jpg","L’antichissimo Ellenikon viene coltivato in Campania sin dal VI secolo a.C..
Di colore rosso rubino e profumo intenso, invitante ed asciutto, l’Aglianico è un vino dal gusto gradevole, leggermente tannico, con aromi persistenti di frutti selvatici.Abbinamenti consigliati: selvaggina, carni rosse e formaggi stagionati."),
("013", "Fiano Campania IGT", 5.50,"spumante", "https://www.collinedelsole.it/wp-content/uploads/2019/01/Campania-Fiano-1-300x300.jpg","Il carattere amabile e schietto del Fiano Campania IGT è servito in tavola, un bianco affabile dall’aroma tipicamente fresco e luminoso, fidato compagno del bere quotidiano.La qualità di questo bianco è garantita dall’origine delle uve che lo producono, dirette discendenti della latina Vitis Apiana (Fiano), tradizionalmente allevata in Irpinia.Esse danno vita a Montesole Campania Fiano, facilmente riconoscibile dal suo caratteristico, intenso ed elegante aroma fruttato. Agli occhi spicca un giallo paglierino chiaro, al naso i sentori di melone bianco e frutta fresca sono accompagnati dalla tipica nota minerale. Il sapore asciutto e armonico lo rende compagno ideale di primi piattti leggeri, zuppe di pesce, merluzzo e carni bianche al cartoccio."),
("014", "Falanghina del Beneventano IGT", 5.50,"ross", "https://www.collinedelsole.it/wp-content/uploads/2019/01/FALANGHINA-DEL-BENEVENTANO-1-300x300.jpg","Vino bianco ben strutturato ed armonico, risultato della vinificazione di uve Falanghina coltivate nella zona del Benevantano. Colore giallo paglierino, profumo intenso e persistente, fruttato con sentori floreali. Gusto secco ed equilibrato con buona struttura. Adatto ad antipasti, zuppe e piatti di pesce in genere, carni bianche e formaggi freschi. Servire a temperatura di circa 10°C.");

insert into utente values 
(codice, "admin", "admin", "admin", "contrada casale bosco", 81085, 3314335956, "Password1.?", 63, 1,"Caserta"),
(codice, "peppe", "cammarieppe", "iozzacchillo", "contrada casale bosco", 81085, 3314335956, "Password1.?", 63, 0,"Caserta");

UPDATE utente SET nome="peppe",cognome="camilla", passwordUtente="Password1.?", citta="caserta", telefono="3310000000", cap=81025, civico=9 WHERE nomeUtente="admin";

select * from utente;

select * from articolocarrello;  



